### ISSUE TITLE
Looks like all tst server api are failing

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#1643]
![Screenshot 2024-08-19 at 12 10 50 PM](https://github.com/user-attachments/assets/d22cea9b-e5aa-453f-8ca7-46a7c798c537)

**Comment by rykahsay** [comment]
Resolved

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
It is still failing.
If I try using it from local server(frontend) then api fail.
![Screenshot 2024-08-19 at 1 28 15 PM](https://github.com/user-attachments/assets/e05a4104-a64a-427e-acf9-751261a220f2)

Also, tst server fails if I try to use tst url.
![Screenshot 2024-08-19 at 1 28 39 PM](https://github.com/user-attachments/assets/fbd88732-ab14-4f2f-8414-fe5824bec6e0)

**Comment by rykahsay** [comment]
tst seems to be working now, it's the prd that is bad now

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
tst server failing again. Please check.

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
tst server is now having certificate issue, please have a look.

**Comment by sujeetvkulkarni** [comment]
done.
