### ISSUE TITLE
Identify why certain TableMaker GTC Accessions come up with: "glycan_not_in_masterlist"

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#2209]
13 GTC accessions are coming up with the error "glycan_not_in_masterlist": 

```
G58499PY
G41897XG
G79250OU
G54226NT
G65710JF
G30468ZC
G53719RV
G53416QV
G79156QW
G30370MC
G98992TC
G54302DV
G01113QL
```

These glycans appear to be present within `/data/projects/glygen/downloads/glycan_list/current/glytoucan_allacc.txt`

HOWEVER, they are NOT present within `/data/projects/glygen/downloads/glytoucan/current/export/allglycan.tsv`

There may have been some filtering conducted to remove these GTC accessions. These GTC accessions also do not already exist within GlyGen as well.

**Comment by edwardsnj** [comment]
Short answer, the files at https://data.glygen.org/ln2downloads/tablemaker/ have no filename extension. At least when I implemented it, I observed them to have extension .txt (and I implemented code specifically for this, since it was a mismatch with the CSV parsing needed!). Now when I look they have no extension. The extension should probably be .csv. Nevertheless, these accessions were not "forced" in the GlycanData set because they were not successfully incorporated from these files. I have fixed the bug at my end, so that it now downloads the files with no extension. If you change the names of these files, including extension, please let me know.

**Comment by ubhuiyan** [comment]
Thank you, Nathan! I think after my second download of the TableMaker data the extension may have dropped off. I have notified Rene and Sena about this and possibly adding the extension. If they happen to add the CSV extension I will make a note of it and notify you on one of our dev calls for 2.9.

**Comment by ubhuiyan** [comment]
@edwardsnj I should have asked, are the bug fixes you've made available for me to download? I redownloaded the GlyTouCan exports yesterday, but it appears the missing GTCs are still not present in `allglycan.tsv`.

**Comment by edwardsnj** [comment]
@ubhuiyan I didn't suggest that I would regenerate a completely updated Glycan-Data-Export, just that I have fixed my code for the current filenames of those datasets so that it will work in the next release. If a new export is desired, that will take some time.

**Comment by ReneRanzinger** [comment]
What is the decision on this? I am fine with waiting till 2.9 as long as at least some TableMaker data makes it into 2.8

**Comment by ubhuiyan** [comment]
We will proceed with what we have for 2.8. I will make sure all GTCs are integrated for 2.9.
