### ISSUE TITLE
status_many api does not return corresponding job details.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#2246]
Add new api:
https://api.tst.glygen.org/job/addnew
Payload:
```
{
  "jobtype": "isoform_mapper",
  "intable": [
    [
      "isoform_ac",
      "amino_acid_pos",
      "amino_acid"
    ],
    [
      "A6NJB7-2",
      "3",
      "T"
    ],
    [
      "A6NJB7-2",
      "8",
      "S"
    ],
    [
      "P08697-2",
      "36",
      ""
    ]
  ],
  "parameters": "{}"
}
```

response:
```
{
    "submission": "new",
    "status": {
        "tsid": "12",
        "status": "running",
        "cmd_status": "/usr/local/bin/ts -s 12",
        "cmd_info": "/usr/local/bin/ts -i 12",
        "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/tst/jobs/244371169/input.csv",
        "slots_required": "1",
        "enqueue_time": "Tue Apr  1 14:00:29 2025",
        "start_time": "Tue Apr  1 14:00:29 2025",
        "time_running": "0.160346s"
    },
    "jobid": 244371169
}
```
API:
https://api.tst.glygen.org/job/status_many/?query={"jobidlist":[244371169]}

response:
```
{"status_obj_list": [{}]}
```

status_many does not return object for the job.
This behavior was observed for blast and isoform jobs.

**Comment by sujeetvkulkarni** [comment]
Issue present on both beta and test.

**Comment by rykahsay** [comment]
Can you test this now on beta and let me know if still persists?

**Comment by sujeetvkulkarni** [comment]
the issue persists for isoform job. When addnew api responds job status as running then status_many api is not responding corresponding job details.

API:
https://beta-api.glygen.org/job/addnew

payload:
```
{
  "jobtype": "isoform_mapper",
  "intable": [
    [
      "isoform_ac",
      "amino_acid_pos",
      "amino_acid"
    ],
    [
      "A6NJB7-2",
      "3",
      ""
    ],
    [
      "A6NJB7-2",
      "8",
      "S"
    ],
    [
      "P08697-2",
      "36",
      ""
    ]
  ],
  "parameters": "{}"
}
```

response:
```
{
    "submission": "new",
    "status": {
        "tsid": "11",
        "status": "running",
        "cmd_status": "/usr/local/bin/ts -s 11",
        "cmd_info": "/usr/local/bin/ts -i 11",
        "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/beta/jobs/2800019/input.csv",
        "slots_required": "1",
        "enqueue_time": "Mon Apr  7 17:44:56 2025",
        "start_time": "Mon Apr  7 17:44:56 2025",
        "time_running": "0.236139s"
    },
    "jobid": 2800019
}
```

API:

https://beta-api.glygen.org/job/status_many/?query={"jobidlist":[2800019]}

![Image](https://github.com/user-attachments/assets/7cce48b6-66f6-418f-8007-b951504dcfbc)

**Comment by rykahsay** [comment]
Can you try now? It is working for me (as shown below)

```
$ http POST :4442/job/addnew/ < tests/examples/job/job_addnew.isoform_mapper.x.json 
HTTP/1.1 200 OK
Connection: close
Content-Length: 422
Content-Type: application/json
Date: Thu, 10 Apr 2025 00:15:52 GMT
Server: gunicorn

{
    "jobid": 2800021,
    "status": {
        "cmd_info": "/usr/local/bin/ts -i 0",
        "cmd_status": "/usr/local/bin/ts -s 0",
        "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/beta/jobs/2800021/input.csv",
        "enqueue_time": "Thu Apr 10 00:15:51 2025",
        "slots_required": "1",
        "start_time": "Thu Apr 10 00:15:51 2025",
        "status": "running",
        "time_running": "0.246995s",
        "tsid": "0"
    },
    "submission": "new"
}
```


```
$ http POST :4442/job/status_many/ < tests/examples/job/job_status_many.json
HTTP/1.1 200 OK
Connection: close
Content-Length: 630
Content-Type: application/json
Date: Thu, 10 Apr 2025 00:16:17 GMT
Server: gunicorn

{
    "status_obj_list": [
        {
            "cmd_info": "/usr/local/bin/ts -i 0",
            "cmd_status": "/usr/local/bin/ts -s 0",
            "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/beta/jobs/2800021/input.csv",
            "end_time": "Thu Apr 10 00:15:57 2025",
            "enqueue_time": "Thu Apr 10 00:15:51 2025",
            "exit_status": "died with exit code 0",
            "jobid": 2800021,
            "output_files": [
                {
                    "format": "tsv",
                    "url": "https://beta-data.glygen.org/ln2data/userdata/beta/jobs/2800021/output.tsv"
                }
            ],
            "result_count": 4,
            "slots_required": "1",
            "start_time": "Thu Apr 10 00:15:51 2025",
            "status": "finished",
            "time_run": "5.764251s",
            "tsid": "0"
        }
    ]
}

```

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
The issue still exists and after structure search change I noticed the issue with structure search job along with isoform job. 
This happens if the addnew api returns "status": "running" and then status_many api is called in loop to check the status. 
If the **status** is **"running"** for the job then **status_many api returns empty job object** for the job id.
If the **status** is **"finished"** for the job the **status_many api returns proper job object** as response.

1. You have to create a new isoform/structure search job, so addnew api returns running status for the job.
2. Either try to immediately check with status_many api for the job status or have a job which takes time to finish.
3. Then in case job is still running status_many api will returns empty job object - which should not happen.
     But if job is finished then the status_many api returns proper job object which is expected behavior.

**1. Below are screen shots for isoform job.**

API:
https://beta-api.glygen.org/job/addnew

Make some modifications so that new job is created and it takes time to finish and then quickly call status_many api.

Payload:
```
{
  "jobtype": "isoform_mapper",
  "intable": [
    [
      "isoform_ac",
      "amino_acid_pos",
      "amino_acid"
    ],
    [
      "A6NJB7-2",
      "3",
      "T"
    ],
    [
      "A6NJB7-2",
      "8",
      "S"
    ],
    [
      "P08697-2",
      "3",
      ""
    ]
  ],
  "parameters": "{}"
}
```

add new api Response:
<img width="1532" alt="Image" src="https://github.com/user-attachments/assets/9f9212bb-218b-4dc0-96a7-1ec9f3145dc9" />



status_many api payload:

<img width="1546" alt="Image" src="https://github.com/user-attachments/assets/9bc29c96-191a-42ed-a5b6-57a491cd294d" />

status_many api response:

<img width="1537" alt="Image" src="https://github.com/user-attachments/assets/0d2ff87b-9c4d-4f84-ba1b-c937673ecd9a" />



**2. Similar case is observed with structure search/sub structure search job.**

API:
https://beta-api.glygen.org/job/addnew

Make some modifications so that new job is created and it takes time to finish and then quickly call status_many api.

Payload:
```
{
  "jobtype": "structure_search",
  "parameters": {
    "seq": "RES\n1b:b-dglc-HEX-1:5\n2s:n-acetyl\n3b:b-dgal-HEX-1:5\nLIN\n1:1d(2+1)2n\n2:1o(3+1)3",
    "align": "nonreducingend"
  }
}
```

add new api Response:

![Image](https://github.com/user-attachments/assets/c03450b4-cdb7-41a5-9982-5c2a66ffec5c)

status_many api payload:

![Image](https://github.com/user-attachments/assets/5fc15277-92d6-4df5-8ecb-9108e6658c8f)

status_many api response:

![Image](https://github.com/user-attachments/assets/2989954c-bf7c-4c3f-92fd-3ab560f8794e)

**Comment by rykahsay** [comment]
You need to wait (atleast for 5 seconds between the addnew and status_many API calls. Given below is what I did to reproduce the problem and it works if I wait for 5 seconds in between. So, you need to do the same.



```
import json
import requests
import subprocess
import time

in_file = "tests/examples/job/job_addnew.isoform_mapper.x.json"
doc = json.load(open(in_file))
doc["intable"][-1][1] = str(int(doc["intable"][-1][1]) + 1)
with open(in_file, "w") as FW:
    FW.write("%s\n" % (json.dumps(doc, indent=4)))

cmd = "http POST :4442/job/addnew/ < tests/examples/job/job_addnew.isoform_mapper.x.json"
res = subprocess.getoutput(cmd)
res_obj = json.loads(res)
job_id = res_obj["jobid"]
print (json.dumps(res_obj, indent=4))



time.sleep(5)



in_file = "tests/examples/job/job_status_many.json"
doc = {"jobidlist":[job_id]}
with open(in_file, "w") as FW:
    FW.write("%s\n" % (json.dumps(doc, indent=4)))
cmd = "http POST :4442/job/status_many/ < tests/examples/job/job_status_many.json"
res = subprocess.getoutput(cmd)
res_obj = json.loads(res)
print (json.dumps(res_obj, indent=4))

```

**Comment by sujeetvkulkarni** [comment]
@rykahsay ok, I will add wait but I think addnew api should have that wait inbuilt before returning but again there is no point in keeping server busy unnecessarily.

**Comment by sujeetvkulkarni** [comment]
I tried with 5 seconds and 10 seconds time gap between response of addnew api call and status_many api call.
But noticed if addnew api returns job with running status then status_many api returns empty object.
The behavior is not consistent once I noticed addnew api returned running status and status_many api returned finished status. 

So, you would have to submit a new job so that add new api returns running status for the job and job takes time to finish forcing status_many api to return running status on first call.

https://beta-api.glygen.org/job/addnew
Payload
```
{
  "jobtype": "isoform_mapper",
  "sequence": "MDTQGPVSQPFQQPEKPGRVRRRKTRRERNKALVGSRRPLAHHDPPVAIRDPPVVPTASKLVVITQGRLSREHRGLFNHEVKSLDVARLLSSGTLVPGSPTLPAKPSPSPGRAQEPAPRSRDKENQVPGGSGPGPPSSPELSGVGQLLAELQCQLSLPQAFPRRNLIQDARDAIVHTLQACHGCVPDLALVLRGCQPPLPGERPSCPCTPLSFVGSSSASLYASFLCARGQAWGL",
  "intable": [
    [
      "amino_acid_pos",
      "amino_acid"
    ],
    [
      "3",
      "K"
    ],
    [
      "8",
      "S"
    ]
  ],
  "parameters": "{}"
}
```

![Image](https://github.com/user-attachments/assets/3db3a246-d0af-4d56-b5dc-91c0687ba4d6)

![Image](https://github.com/user-attachments/assets/b27b4b50-bfa7-418a-8741-6d69e4b39f55)


**Same is observed for  structure_search job.**

API:
https://beta-api.glygen.org/job/addnew

Payload:
```
{
  "jobtype": "structure_search",
  "parameters": {
    "seq": "RES\n1b:b-dglc-HEX-1:5\n2s:n-acetyl\n3b:b-dgal-HEX-1:5\nLIN\n1:1d(2+1)2n\n",
    "align": "wholeglycan"
  }
}
```

https://beta-api.glygen.org/job/status_many/?query={"jobidlist":[2800045]}

![Image](https://github.com/user-attachments/assets/1cba9467-280c-4c30-8455-9f9a3efa60ca)

**Comment by sujeetvkulkarni** [comment]
Also, below api call returns empty object. Looks in case there is error it returns empty object too.
https://beta-api.glygen.org/job/status_many/?query={"jobidlist":[2800045]}

response:
{"status_obj_list": [{}]}

**Comment by sujeetvkulkarni** [comment]
The above mentioned behavior is with structure search and isoform jobs when status is either running or there is an error case for the job and status_many api is called.

**Comment by rykahsay** [comment]
I have fixed it, you will get the following:

```
$ http POST :4442/job/status_many/ < tests/examples/job/job_status_many.json
HTTP/1.1 200 OK
Connection: close
Content-Length: 102
Content-Type: application/json
Date: Wed, 16 Apr 2025 23:28:44 GMT
Server: gunicorn

{
    "status_obj_list": [
        {
            "error_list": [
                {
                    "error_code": "Motif is not a structure"
                }
            ],
            "jobid": 2800045
        }
    ]
}

```

**Comment by sujeetvkulkarni** [comment]
Is this fixed only specific to this job (2800045) ? Because I can still see empty objects when the status should running, error in isoform, structure search jobs.

**For structure search,**

![Image](https://github.com/user-attachments/assets/ed9d0eb4-e935-4907-b530-badffb83ba00)

![Image](https://github.com/user-attachments/assets/712caeb8-62b8-44a2-954c-dd421c6e517a)

empty job result for 2800059 job id.
https://beta-api.glygen.org/job/status_many/?query={"jobidlist":[2800058,2800005,2800059]}

```
{
    "status_obj_list": [
        {
            "jobid": 2800058,
            "error_list": [
                {
                    "error_code": "Motif is not a structure"
                }
            ]
        },
        {
            "tsid": "0",
            "status": "finished",
            "cmd_status": "/usr/local/bin/ts -s 0",
            "cmd_info": "/usr/local/bin/ts -i 0",
            "exit_status": "died with exit code 0",
            "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/beta/jobs/2800021/input.csv",
            "slots_required": "1",
            "enqueue_time": "Thu Apr 10 00:15:51 2025",
            "start_time": "Thu Apr 10 00:15:51 2025",
            "end_time": "Thu Apr 10 00:15:57 2025",
            "time_run": "5.764251s",
            "jobid": 2800005,
            "result_count": 12,
            "output_files": [
                {
                    "format": "json",
                    "url": "https://beta-data.glygen.org/ln2data/userdata/beta/jobs/2800005/output.json"
                }
            ]
        },
        {}
    ]
}
```


**For isoform,**

https://beta-api.glygen.org/job/addnew

Payload
```
{
  "jobtype": "isoform_mapper",
  "sequence": "MDTQGPVSQPFQQPEKPGRVRRRKTRRERNKALVGSRRPLAHHDPPVAIRDPPVVPTASKLVVITQGRLSREHRGLFNHEVKSLDVARLLSSGTLVPGSPTLPAKPSPSPGRAQEPAPRSRDKENQVPGGSGPGPPSSPELSGVGQLLAELQCQLSLPQAFPRRNLIQDARDAIVHTLQACHGCVPDLALVLRGCQPPLPGERPSCPCTPLSFVGSSSASLYASFLCARGQAWGL",
  "intable": [
    [
      "amino_acid_pos",
      "amino_acid"
    ],
    [
      "3",
      ""
    ],
    [
      "8",
      "S"
    ]
  ],
  "parameters": "{}"
}
```

response
```
{
    "submission": "new",
    "status": {
        "tsid": "1",
        "status": "running",
        "cmd_status": "/usr/local/bin/ts -s 1",
        "cmd_info": "/usr/local/bin/ts -i 1",
        "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/beta/jobs/2800060/input.csv",
        "slots_required": "1",
        "enqueue_time": "Fri Apr 18 23:32:39 2025",
        "start_time": "Fri Apr 18 23:32:39 2025",
        "time_running": "0.282550s"
    },
    "jobid": 2800060
}
```
addnew api took 15 seconds to return

![Image](https://github.com/user-attachments/assets/fa920b47-4c40-47c8-bb35-ccf84731681f)

the job status was running then the status_many api is called,

https://beta-api.glygen.org/job/status_many/?query={"jobidlist":[2800060]}
response
{"status_obj_list": [{}]}

![Image](https://github.com/user-attachments/assets/61fd1696-7376-447b-bbc0-f3c768858c9a)

**Comment by sujeetvkulkarni** [comment]
To summarize the issue still exists if addnew api returns job status as running and when the status api is called while the job is running in case of structure search or isoform jobs we get empty job object. Eventually the job might return finished status or 
 continue to return empty object as response but while the job is running status_many api return empty ({}) job object for structure search or isoform jobs.

After roughly 5 minutes also jobid 2800059 returns {} object.

https://beta-api.glygen.org/job/status_many/?query={"jobidlist":[2800058,2800005,2800010,2800060,2800059]}

```
{
    "status_obj_list": [
        {
            "jobid": 2800058,
            "error_list": [
                {
                    "error_code": "Motif is not a structure"
                }
            ]
        },
        {
            "tsid": "0",
            "status": "finished",
            "cmd_status": "/usr/local/bin/ts -s 0",
            "cmd_info": "/usr/local/bin/ts -i 0",
            "exit_status": "died with exit code 0",
            "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/beta/jobs/2800021/input.csv",
            "slots_required": "1",
            "enqueue_time": "Thu Apr 10 00:15:51 2025",
            "start_time": "Thu Apr 10 00:15:51 2025",
            "end_time": "Thu Apr 10 00:15:57 2025",
            "time_run": "5.764251s",
            "jobid": 2800005,
            "result_count": 12,
            "output_files": [
                {
                    "format": "json",
                    "url": "https://beta-data.glygen.org/ln2data/userdata/beta/jobs/2800005/output.json"
                }
            ]
        },
        {
            "tsid": "2",
            "status": "finished",
            "cmd_status": "/usr/local/bin/ts -s 2",
            "cmd_info": "/usr/local/bin/ts -i 2",
            "exit_status": "died with exit code 0",
            "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/beta/jobs/2800010/input.csv",
            "slots_required": "1",
            "enqueue_time": "Wed Apr  2 18:54:56 2025",
            "start_time": "Wed Apr  2 18:54:56 2025",
            "end_time": "Wed Apr  2 18:55:00 2025",
            "time_run": "4.598812s",
            "jobid": 2800010,
            "result_count": 2,
            "output_files": [
                {
                    "format": "tsv",
                    "url": "https://beta-data.glygen.org/ln2data/userdata/beta/jobs/2800010/output.tsv"
                }
            ]
        },
        {
            "tsid": "1",
            "status": "finished",
            "cmd_status": "/usr/local/bin/ts -s 1",
            "cmd_info": "/usr/local/bin/ts -i 1",
            "exit_status": "died with exit code 0",
            "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/beta/jobs/2800060/input.csv",
            "slots_required": "1",
            "enqueue_time": "Fri Apr 18 23:32:39 2025",
            "start_time": "Fri Apr 18 23:32:39 2025",
            "end_time": "Fri Apr 18 23:32:44 2025",
            "time_run": "5.535255s",
            "jobid": 2800060,
            "result_count": 2,
            "output_files": [
                {
                    "format": "tsv",
                    "url": "https://beta-data.glygen.org/ln2data/userdata/beta/jobs/2800060/output.tsv"
                }
            ]
        },
        {}
    ]
}
```

**Comment by sujeetvkulkarni** [comment]
I have created new job payloads for you to test. So please try with below payloads,

https://beta-api.glygen.org/job/addnew
Payload for isoform job
```
{
  "jobtype": "isoform_mapper",
  "sequence": "MDTQGPVSQPFQQPEKPGRVRRRKTRRERNKALVGSRRPLAHHDPPVAIRDPPVVPTASKLVVITQGRLSREHRGLFNHEVKSLDVARLLSSGTLVPGSPTLPAKPSPSPGRAQEPAPRSRDKENQVPGGSGPGPPSSPELSGVGQLLAELQCQLSLPQAFPRRNLIQDARDAIVHTLQACHGCVPDLALVLRGCQPPLPGERPSCPCTPLSFVGSSSASLYASFLCARGQAWGL",
  "intable": [
    [
      "amino_acid_pos",
      "amino_acid"
    ],
    [
      "3",
      "T"
    ],
    [
      "8",
      "H"
    ]
  ],
  "parameters": "{}"
}
```

https://beta-api.glygen.org/job/addnew

Payload for structure search job
```
{
  "jobtype": "structure_search",
  "parameters": {
    "seq": "RES\n1b:b-dglc-HEX-1:5\n2s:n-acetyl\n3b:b-1:7\nLIN\n1:1d(2+1)2n\n2:1o(3+1)3d",
    "align": "substructure"
  }
}
```
Also check below structure search job
https://beta-api.glygen.org/job/status_many/?query={"jobidlist":[2800059]

**Comment by rykahsay** [comment]
Can you try now?

**Comment by sujeetvkulkarni** [comment]
@rykahsay In case of status_many api object structure when status is "running" for structure, isoform and BLAST job is changed, which needs correction.
Currently data is inside "status_obj": {} when the the status is running which should not be case for status_many.

Current object structure,
https://api.glygen.org/job/status_many/?query={"jobidlist":[2800002]}
```
{
    "status_obj_list": [
        {
            "jobid": 2800002,
            "status_obj": {
                "tsid": "1",
                "status": "running",
                "cmd_status": "/usr/local/bin/ts -s 1",
                "cmd_info": "/usr/local/bin/ts -i 1",
                "exit_status": "died with exit code 0",
                "command": "python /app/job_submitters/structure_search.py -i /data/shared/glygen//userdata/prd/jobs/2800002/input.json -o /data/shared/glygen//userdata/prd/jobs/2800002/output.json -u http://172.17.0.12:10980",
                "slots_required": "1",
                "enqueue_time": "Mon Apr 28 16:07:31 2025",
                "start_time": "Mon Apr 28 16:07:31 2025",
                "end_time": "Mon Apr 28 16:07:34 2025",
                "time_run": "2.613186s",
                "jobid": 2800002
            }
        }
    ]
}
```

![Image](https://github.com/user-attachments/assets/bb96949c-0a26-4f1e-886e-263217d17ae1)


Same is happening for isoform job.
https://api.glygen.org/job/status_many/?query={"jobidlist":[2800003]}

![Image](https://github.com/user-attachments/assets/fbe43906-94d5-43fb-b5fe-01cad38fba13)

Similar is happening for BLAST job.
https://api.glygen.org/job/status_many/?query={"jobidlist":[2800006]}

![Image](https://github.com/user-attachments/assets/6f359015-7006-4ffd-b916-b047ec2edfaa)

The data should not be is inside "status_obj": {} for status_many api
It should be like below as agreed earlier

```
{
    "status_obj_list": [
        {
                "tsid": "1",
                "status": "running",
                "cmd_status": "/usr/local/bin/ts -s 1",
                "cmd_info": "/usr/local/bin/ts -i 1",
                "exit_status": "died with exit code 0",
                "command": "python /app/job_submitters/structure_search.py -i /data/shared/glygen//userdata/prd/jobs/2800002/input.json -o /data/shared/glygen//userdata/prd/jobs/2800002/output.json -u http://172.17.0.12:10980",
                "slots_required": "1",
                "enqueue_time": "Mon Apr 28 16:07:31 2025",
                "start_time": "Mon Apr 28 16:07:31 2025",
                "end_time": "Mon Apr 28 16:07:34 2025",
                "time_run": "2.613186s",
                "jobid": 2800002
        }
    ]
}
```

error case response needs to be:
```
{
            "jobid": 2800058,
            "error_list": [
                {
                    "error_code": "Motif is not a structure"
                }
            ]
        },
```

The data appears properly when the status is changes to finished

![Image](https://github.com/user-attachments/assets/250ac1c5-4766-455f-b57a-5e049d006932)

For /job/addnew api existing object structure is fine.

**Comment by rykahsay** [comment]
I have tried to fix it:

First issue
```
{
    "status_obj_list": [
        {
            "tsid": "0",
            "status": "running",
            "cmd_status": "/usr/local/bin/ts -s 0",
            "cmd_info": "/usr/local/bin/ts -i 0",
            "command": "python /app/job_submitters/isoform_mapper.py -i /data/shared/glygen//userdata/beta/jobs/2800092/input.csv",
            "slots_required": "1",
            "enqueue_time": "Fri May  2 17:37:00 2025",
            "start_time": "Fri May  2 17:37:00 2025",
            "time_running": "1.579803s",
            "jobid": 2800092
        },
        {
            "tsid": "1",
            "status": "queued",
            "cmd_status": "/usr/local/bin/ts -s 1",
            "cmd_info": "/usr/local/bin/ts -i 1",
            "command": "python /app/job_submitters/structure_search.py -i /data/shared/glygen//userdata/beta/jobs/2800093/input.json -o /data/shared/glygen//userdata/beta/jobs/2800093/output.json -u http://172.17.0.13:10990",
            "slots_required": "1",
            "enqueue_time": "Fri May  2 17:37:01 2025",
            "jobid": 2800093
        }
    ]
}
```


Second issue
```
$ http POST :4442/job/status_many/ < tests/examples/job/job_status_many.json
HTTP/1.1 200 OK
Connection: close
Content-Length: 93
Content-Type: application/json
Date: Fri, 02 May 2025 17:54:33 GMT
Server: gunicorn

{
    "status_obj_list": [
        {
            "error_list": [
                {
                    "error_code": "Unable to parse"
                }
            ],
            "jobid": 2800096
        }
    ]
}

```

**Comment by sujeetvkulkarni** [comment]
@rykahsay this is working as expected. But what is status "queued" showed in above example? Can we use "running" status in case of "queued" too. I have not handled "queued" status.

**Comment by rykahsay** [comment]
Done, please test

**Comment by sujeetvkulkarni** [comment]
Fixed, closing.
