### ISSUE TITLE
Exception error - pymongo.errors.OperationFailure: text index required for $text query

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#3025]
**12/18/25**

ID  URBSXT
TS  2025-12-17 10:10:59 EST-0500
LN  Traceback (most recent call last):
LN    File "/app/dsviewer/document.py", line 169, in get_many_text_search
LN      res_obj["recordlist"]  = list(mongo_dbh[coll_name].find(qry_obj,prj_obj).skip(offset).limit(limit))
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
LN      if len(self.__data) or self._refresh():
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1073, in _refresh
LN      self.__send_message(q)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
LN      address=self.__address)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
LN      exhaust=exhaust)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
LN      return func(session, server, sock_info, slave_ok)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
LN      unpack_res)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
LN      _check_command_response(first)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
LN      raise OperationFailure(msg % errmsg, code, response)
LN  pymongo.errors.OperationFailure: text index required for $text query (no such collection 'glydb.c_bco_v-2.10.1')
//

ID  KZ4OJZ
TS  2025-12-17 10:11:23 EST-0500
LN  Traceback (most recent call last):
LN    File "/app/dsviewer/document.py", line 169, in get_many_text_search
LN      res_obj["recordlist"]  = list(mongo_dbh[coll_name].find(qry_obj,prj_obj).skip(offset).limit(limit))
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
LN      if len(self.__data) or self._refresh():
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1073, in _refresh
LN      self.__send_message(q)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
LN      address=self.__address)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
LN      exhaust=exhaust)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
LN      return func(session, server, sock_info, slave_ok)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
LN      unpack_res)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
LN      _check_command_response(first)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
LN      raise OperationFailure(msg % errmsg, code, response)
LN  pymongo.errors.OperationFailure: text index required for $text query (no such collection 'glydb.c_bco_v-2.10.1')
//

ID  6F5L33
TS  2025-12-17 10:11:38 EST-0500
LN  Traceback (most recent call last):
LN    File "/app/dsviewer/document.py", line 169, in get_many_text_search
LN      res_obj["recordlist"]  = list(mongo_dbh[coll_name].find(qry_obj,prj_obj).skip(offset).limit(limit))
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
LN      if len(self.__data) or self._refresh():
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1073, in _refresh
LN      self.__send_message(q)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
LN      address=self.__address)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
LN      exhaust=exhaust)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
LN      return func(session, server, sock_info, slave_ok)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
LN      unpack_res)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
LN      _check_command_response(first)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
LN      raise OperationFailure(msg % errmsg, code, response)
LN  pymongo.errors.OperationFailure: text index required for $text query (no such collection 'glydb.c_bco_v-2.10.1')
//

**Comment by rykahsay** [comment]
Addressed by creating the required $text index

```
res = dbh["c_dsindex"].create_index([("$**", pymongo.TEXT)])
```

**Comment by ReneRanzinger** [comment]
This error is back for 2.11

**5/7/26**
ID  KDTBZ6
TS  2026-05-07 12:34:03 EDT-0400
LN  Traceback (most recent call last):
LN    File "/app/dsviewer/document.py", line 169, in get_many_text_search
LN      res_obj["recordlist"]  = list(mongo_dbh[coll_name].find(qry_obj,prj_obj).skip(offset).limit(limit))
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
LN      if len(self.__data) or self._refresh():
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1073, in _refresh
LN      self.__send_message(q)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
LN      address=self.__address)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
LN      exhaust=exhaust)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
LN      return func(session, server, sock_info, slave_ok)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
LN      unpack_res)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
LN      _check_command_response(first)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
LN      raise OperationFailure(msg % errmsg, code, response)
LN  pymongo.errors.OperationFailure: text index required for $text query (no such collection 'glydb.c_bco_v-2.11.1')
//

**Comment by ReneRanzinger** [comment]
**5/8/26**
ID  6YC3GS
TS  2026-05-08 06:18:54 EDT-0400
LN  Traceback (most recent call last):
LN    File "/app/dsviewer/document.py", line 169, in get_many_text_search
LN      res_obj["recordlist"]  = list(mongo_dbh[coll_name].find(qry_obj,prj_obj).skip(offset).limit(limit))
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
LN      if len(self.__data) or self._refresh():
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1073, in _refresh
LN      self.__send_message(q)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
LN      address=self.__address)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
LN      exhaust=exhaust)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
LN      return func(session, server, sock_info, slave_ok)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
LN      unpack_res)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
LN      _check_command_response(first)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
LN      raise OperationFailure(msg % errmsg, code, response)
LN  pymongo.errors.OperationFailure: text index required for $text query (no such collection 'glydb.c_bco_v-2.11.1')
//

**5/9/26**
ID  E4N7Z0
TS  2026-05-09 15:14:01 EDT-0400
LN  Traceback (most recent call last):
LN    File "/app/dsviewer/document.py", line 169, in get_many_text_search
LN      res_obj["recordlist"]  = list(mongo_dbh[coll_name].find(qry_obj,prj_obj).skip(offset).limit(limit))
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
LN      if len(self.__data) or self._refresh():
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1073, in _refresh
LN      self.__send_message(q)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
LN      address=self.__address)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
LN      exhaust=exhaust)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
LN      return func(session, server, sock_info, slave_ok)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
LN      unpack_res)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
LN      _check_command_response(first)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
LN      raise OperationFailure(msg % errmsg, code, response)
LN  pymongo.errors.OperationFailure: text index required for $text query (no such collection 'glydb.c_bco_v-2.11.1')
//

**Comment by ReneRanzinger** [comment]
**5/10/26**
ID  G2YY6J
TS  2026-05-10 23:54:53 EDT-0400
LN  Traceback (most recent call last):
LN    File "/app/dsviewer/document.py", line 169, in get_many_text_search
LN      res_obj["recordlist"]  = list(mongo_dbh[coll_name].find(qry_obj,prj_obj).skip(offset).limit(limit))
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
LN      if len(self.__data) or self._refresh():
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1073, in _refresh
LN      self.__send_message(q)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
LN      address=self.__address)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
LN      exhaust=exhaust)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
LN      return func(session, server, sock_info, slave_ok)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
LN      unpack_res)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
LN      _check_command_response(first)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
LN      raise OperationFailure(msg % errmsg, code, response)
LN  pymongo.errors.OperationFailure: text index required for $text query (no such collection 'glydb.c_bco_v-2.11.1')
//

**Comment by ReneRanzinger** [comment]
**5/11/26**
ID  R3SGHL
TS  2026-05-11 02:40:03 EDT-0400
LN  Traceback (most recent call last):
LN    File "/app/dsviewer/document.py", line 169, in get_many_text_search
LN      res_obj["recordlist"]  = list(mongo_dbh[coll_name].find(qry_obj,prj_obj).skip(offset).limit(limit))
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
LN      if len(self.__data) or self._refresh():
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1073, in _refresh
LN      self.__send_message(q)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
LN      address=self.__address)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
LN      exhaust=exhaust)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
LN      return func(session, server, sock_info, slave_ok)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
LN      unpack_res)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
LN      _check_command_response(first)
LN    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
LN      raise OperationFailure(msg % errmsg, code, response)
LN  pymongo.errors.OperationFailure: text index required for $text query (no such collection 'glydb.c_bco_v-2.11.1')
//
