### ISSUE TITLE
Exception error protein search  - IndexError: list index out of range

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#3054]
**12/24/2025**

ID  MSJJAL
TS  2025-12-23 04:47:06 EST-0500
LN  Traceback (most recent call last):
LN    File "/app/glygen/glycan.py", line 87, in post
LN      res_obj = glycan_search(req_obj, config_obj)
LN    File "/app/glygen/glycan_apilib.py", line 290, in glycan_search
LN      hit_record_list = hit_dict[sf_list[0]]
LN  IndexError: list index out of range
//

ID  IEPLQ6
TS  2025-12-23 21:10:57 EST-0500
LN  Traceback (most recent call last):
LN    File "/app/glygen/protein.py", line 87, in post
LN      res_obj = protein_search(req_obj, config_obj)
LN    File "/app/glygen/protein_apilib.py", line 180, in protein_search
LN      record_list = hit_dict[sf_list[0]]
LN  IndexError: list index out of range
//

**Comment by rykahsay** [comment]
Fixed

**Comment by ReneRanzinger** [comment]
This problem is back.

**1/4/2026**
ID  SWRWIN
TS  2026-01-04 00:06:10 EST-0500
LN  Traceback (most recent call last):
LN    File "/app/glygen/glycan.py", line 87, in post
LN      res_obj = glycan_search(req_obj, config_obj)
LN    File "/app/glygen/glycan_apilib.py", line 290, in glycan_search
LN      hit_record_list = hit_dict[sf_list[0]]
LN  IndexError: list index out of range
//

**Comment by ReneRanzinger** [comment]
**1/3/2026**
ID  SFAW2M
TS  2026-01-03 23:07:44 EST-0500
LN  Traceback (most recent call last):
LN    File "/app/glygen/glycan.py", line 87, in post
LN      res_obj = glycan_search(req_obj, config_obj)
LN    File "/app/glygen/glycan_apilib.py", line 290, in glycan_search
LN      hit_record_list = hit_dict[sf_list[0]]
LN  IndexError: list index out of range
//

**Comment by ReneRanzinger** [comment]
**12/29/2025**
ID  SJ9A24
TS  2025-12-29 07:03:52 EST-0500
LN  Traceback (most recent call last):
LN    File "/app/glygen/glycan.py", line 87, in post
LN      res_obj = glycan_search(req_obj, config_obj)
LN    File "/app/glygen/glycan_apilib.py", line 290, in glycan_search
LN      hit_record_list = hit_dict[sf_list[0]]
LN  IndexError: list index out of range
//

**Comment by rykahsay** [comment]
I have tried to fix it again
